#!/bin/bash
##
## This file is part of the BeagleLogic project
##
## Copyright (C) 2014 Kumar Abhishek <abhishek@theembeddedkitchen.net>
## 
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 3 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program; if not, write to the Free Software
## Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
##

## This script deploys anything under the /deploy folder to the BeagleBone Black
## Change BEAGLEBONE_HOST to the IP Address of the BeagleBone Black
ROOT="root"
BEAGLEBONE_HOST="192.168.7.2"

scp -r ./deploy/* $ROOT@$BEAGLEBONE_HOST:/ &> deploy.log~

if test $? = 0; then
	echo "Deploy successful."
else
	echo "Error while deploying."
fi

