

/* This file contains the PRU instructions in a C array which are to  */
/* be downloaded from the host CPU to the PRU instruction memory.     */
/* This file is generated by the PRU assembler.                       */

const unsigned int PRUcode[] =  {
     0x91042480,
     0x1d04e0e0,
     0x81042480,
     0x240002c4,
     0x24200084,
     0xf1002480,
     0x1f03e0e0,
     0xe1002480,
     0x24deadc1,
     0x24beef81,
     0x24feebc4,
     0x24daed84,
     0x240000e2,
     0x242000e3,
     0xe1002281,
     0xe1002384,
     0x240002c4,
     0x24200c84,
     0x240002c3,
     0x24201083,
     0xe1002284,
     0x10e5e5e5,
     0x10e5e5e5,
     0x10e5e5e5,
     0xe1042284,
     0xe1082283,
     0x2400231f,
     0x2a000000 };

